name: py38
channels:
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aria2=1.23.0=0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.11.0=h470a237_1
  - ca-certificates=2025.12.2=h06a4308_0
  - gawk=5.3.1=h5eee18b_0
  - icu=73.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - mmseqs2=18.8cc5c=hd6d6fdc_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.18=h7a1cb2a_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.0.1
      - biopython==1.83
      - bitsandbytes==0.45.5
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - filelock==3.16.1
      - fsspec==2025.3.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.4.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==26.0
      - pandas==2.0.3
      - peft==0.13.2
      - pillow==10.4.0
      - psutil==7.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.17.0
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.2.1+cu121
      - torchaudio==2.2.1+cu121
      - torchvision==0.17.1+cu121
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton==2.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.3
      - urllib3==2.2.3
prefix: /opt/conda/envs/py38
